#This is a sample answer yaml file for the KKE Devops task deploy-voting app on k8s 
#Edit the below codes as per your question details.
#Check this blog https://thirigiri.blogspot.com for kubenetes commands, how to deply this file and how to complete the task.
#I have done a similar task on my own envrinment check above blog for more details.

apiVersion: apps/v1                                                               
kind: Deployment                                                                  
metadata:                                                                         
  creationTimestamp: null                                                         
  labels:                                                                         
    app: worker                                                                   
  name: worker                                                                    
  namespace: vote                                                                 
spec:                                                                             
  replicas: 1                                                                     
  selector:                                                                       
    matchLabels:                                                                  
      app: worker                                                                 
  strategy: {}                                                                    
  template:                                                                       
    metadata:                                                                     
      creationTimestamp: null                                                     
      labels:                                                                     
        app: worker                                                               
    spec:                                                                         
      containers:                                                                 
      - image: kodekloud/examplevotingapp_worker                                  
        name: worker     
